org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft 1.20.1 setup
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)

forge_version=47.4.0
forge_version_range=[47.4.0,)
loader_version_range=[47,)

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

mod_id=mapi
mod_name=MAPI
mod_license=All Rights Reserved
mod_version=1.20.1-1.0.0

mod_group_id=M6FGR.mapi

mod_authors=M6FGR
mod_description=MAPI Core Utility Mod