# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
# Minecraft release version
minecraft_version=1.21.4
minecraft_version_range=[1.21.4, 1.22)

# NeoForge release version
neo_version=21.4.52-beta
neo_version_range=[21.4,)
loader_version_range=[4,)

## Mod Properties
# Unique mod ID (lowercase letters, numbers, and underscores only)
mod_id=mapi
mod_name=MAPI
mod_license=All Rights Reserved
mod_version=1.0.0

# Group ID (lowercase recommended for Maven/Gradle artifact resolution)
mod_group_id=M6FGR.mapi

# Display details
mod_authors=M6FGR
mod_description=MAPI Core Utility Mod